config/routes.rb
Rails.application.routes.draw do
  
  resources :cashbooks
  
  resources :debits do
    get 'summary'
  end

  resources :credits do
    get 'summary'
  end

end

app/models/cashbook.rb
class Cashbook < ActiveRecord::Base
	belongs_to :debit
	belongs_to :credit
end

app/models/credit.rb
class Credit < ActiveRecord::Base
	has_many :cashbooks
end

app/models/debit.rb
class Debit < ActiveRecord::Base
	has_many :cashbooks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cashbooks_controller.rb
class CashbooksController < ApplicationController
  before_action :set_cashbook, only: [:show, :edit, :update, :destroy]

OPENING_BALANCE = 10000.00
  
  # GET /cashbooks
  # GET /cashbooks.json
  def index
    @opening_balance = OPENING_BALANCE
    @cashbooks = Cashbook.all
    @cash_credits = Cashbook.where(credit_id: 1)
    @cash_debits = Cashbook.where(debit_id: 1)
  end

  # GET /cashbooks/1
  # GET /cashbooks/1.json
  def show
  end

  # GET /cashbooks/new
  def new
    @cashbook = Cashbook.new
  end

  # GET /cashbooks/1/edit
  def edit
  end

  # POST /cashbooks
  # POST /cashbooks.json
  def create
    @cashbook = Cashbook.new(cashbook_params)

    respond_to do |format|
      if @cashbook.save
        format.html { redirect_to @cashbook, notice: 'Cashbook was successfully created.' }
        format.json { render :show, status: :created, location: @cashbook }
      else
        format.html { render :new }
        format.json { render json: @cashbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashbooks/1
  # PATCH/PUT /cashbooks/1.json
  def update
    respond_to do |format|
      if @cashbook.update(cashbook_params)
        format.html { redirect_to @cashbook, notice: 'Cashbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @cashbook }
      else
        format.html { render :edit }
        format.json { render json: @cashbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashbooks/1
  # DELETE /cashbooks/1.json
  def destroy
    @cashbook.destroy
    respond_to do |format|
      format.html { redirect_to cashbooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashbook
      @cashbook = Cashbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cashbook_params
      params.require(:cashbook).permit(:date, :debit_id, :credit_id, :amount)
    end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all.order("name")
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  def summary
    @credit_transactions = Credit.where(:id => params[:credit_id]).first.cashbooks
    #@debit_transactions = Debit.where(:id => params[:credit_id]).first.cashbooks
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:name)
    end
end

app/controllers/debits_controller.rb
class DebitsController < ApplicationController
  before_action :set_debit, only: [:show, :edit, :update, :destroy]

  # GET /debits
  # GET /debits.json
  def index
    @debits = Debit.all.order("name")
  end

  def summary
    debit = Debit.where(:id => params[:debit_id]).first
    @transactions_debit = debit.cashbooks
  end

  # GET /debits/1
  # GET /debits/1.json
  def show
  end

  # GET /debits/new
  def new
    @debit = Debit.new
  end

  # GET /debits/1/edit
  def edit
  end

  # POST /debits
  # POST /debits.json
  def create
    @debit = Debit.new(debit_params)

    respond_to do |format|
      if @debit.save
        format.html { redirect_to @debit, notice: 'Debit was successfully created.' }
        format.json { render :show, status: :created, location: @debit }
      else
        format.html { render :new }
        format.json { render json: @debit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debits/1
  # PATCH/PUT /debits/1.json
  def update
    respond_to do |format|
      if @debit.update(debit_params)
        format.html { redirect_to @debit, notice: 'Debit was successfully updated.' }
        format.json { render :show, status: :ok, location: @debit }
      else
        format.html { render :edit }
        format.json { render json: @debit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debits/1
  # DELETE /debits/1.json
  def destroy
    @debit.destroy
    respond_to do |format|
      format.html { redirect_to debits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debit
      @debit = Debit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debit_params
      params.require(:debit).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashbooks_helper.rb
module CashbooksHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/views/cashbooks/_form.html.erb
<%= form_for(@cashbook) do |f| %>
  <% if @cashbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cashbook.errors.count, "error") %> prohibited this cashbook from being saved:</h2>

      <ul>
      <% @cashbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  <head>
  <meta charset="utf-8">
  

Date :  <%= f.date_field :date %> <br>
Debit : <%= f.select :debit_id, Debit.all.collect {|t| [t.name, t.id]}%> <br>
Credit : <%= f.select :credit_id, Credit.all.collect {|t| [t.name, t.id]}, { include_blank: true}%> <br>

Amount :   <%= f.text_field :amount %> <br>
   <%= f.submit "Voucher", class: "btn btn-success btn-small active" %>
   <% end %>

app/views/cashbooks/edit.html.erb
<h1>Editing cashbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cashbook %> |
<%= link_to 'Back', cashbooks_path %>

app/views/cashbooks/index.html.erb
<h3> Cashbook

<%= link_to 'New Transaction', new_cashbook_path, class: "btn btn-mini btn-success active" %> </h3>

<div class="text-right"> Opening Balance as on <strong> <%= @cashbooks.first.created_at.strftime("%d-%b-%Y") %> </strong> is <strong> <%= number_to_currency(@opening_balance, :unit => 'INR ') %> </strong></div> <hr>

  
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr> 
      <th> <div class="text-center"> Date </div> </th> 
      <th> <div class="text-center"> Debit </div> </th>     
      <th> <div class="text-center"> Credit </div> </th>
      <th> <div class="text-center"> Amount </div> </th>
      <th> <div class="text-center"> Balance </div> </th>
      <th colspan="3"> <div class="text-center"> Actions </div> </th>
      
    </tr>
  </thead>

  <tbody>
    <% @cashbooks.each do |cashbook| %>
      <tr>
        <td><%= cashbook.date.strftime("%d-%b-%Y") %></td>
        <%#= link_to cashbook.debit.name, debit_summary_path(:debit_id => cashbook.debit_id) %>
        <td> <%= link_to Debit.find(cashbook.debit_id).name, debit_summary_path(:debit_id => cashbook.debit_id) %> </td>
        <td> <%= link_to Credit.find(cashbook.credit_id).name, credit_summary_path(:credit_id => cashbook.credit_id) %> </td>
        <td> <div class="text-right"> <%= number_to_currency(cashbook.amount, :unit => 'INR ') %> </div> </td>
         <td> <div class="text-right"> <%= number_to_currency(@opening_balance -= cashbook.amount, :unit => 'INR ') %> </div> </td>  
        <td> <div class="text-center"> <%= link_to 'Show', cashbook, class: "btn btn-mini btn-info active" %> </div> </td>
        <td> <div class="text-center"> <%= link_to 'Edit', edit_cashbook_path(cashbook), class: "btn btn-mini btn-warning active" %> </div> </td>
        <td> <div class="text-center"> <%= link_to 'Destroy', cashbook, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger active" %> </div> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cashbooks/ledger.html.erb
this is ledger summary

app/views/cashbooks/new.html.erb
<h3> New transaction </h3>

<%= link_to 'Back', cashbooks_path, class: "btn btn-primary btn-small active" %> </br>

<%= render 'form' %>

app/views/cashbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @cashbook.date %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @cashbook.debit.name %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @cashbook.credit.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cashbook.amount %>
</p>

<%= link_to 'Edit', edit_cashbook_path(@cashbook) %> |
<%= link_to 'Back', cashbooks_path %>

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<h1>Listing credits</h1>

<%= link_to 'New Credit', new_credit_path, class: "btn btn-mini btn-success active" %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.name %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/credits/new.html.erb
<h1>New credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @credit.name %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>

app/views/credits/summary.html.erb
<h3><%= @credit_transactions.first.credit.name %> Ledger Details</h3>


<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th> <div align="center"> Date </div> </th>
      <th> <div align="center"> Ledger </div> </th>      
      <th> <div align="center"> Credit </div> </th>
      <th> <div align="center"> Total </div> </th>      
    </tr>
  </thead>
<% @zero = 0 %> 
  <tbody>
    <% @credit_transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.date.strftime("%d-%b-%Y") %></td>
        
        <td><%= Debit.find(transaction.debit_id).name %></td>
        <td> <div align="right"> <%= number_to_currency(transaction.amount, :unit => 'INR ') %> </div> </td>      
        <td> <div align="right"> <%= number_to_currency(@total = @zero += transaction.amount, :unit => 'INR ') %> </div> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%#= @total %>
<br>

<%= link_to 'back', cashbooks_path, class: "btn btn-mini btn-primary active" %>

app/views/debits/_form.html.erb
<%= form_for(@debit) do |f| %>
  <% if @debit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debit.errors.count, "error") %> prohibited this debit from being saved:</h2>

      <ul>
      <% @debit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debits/edit.html.erb
<h1>Editing debit</h1>

<%= render 'form' %>

<%= link_to 'Show', @debit %> |
<%= link_to 'Back', debits_path %>

app/views/debits/index.html.erb
<h1>Listing debits</h1>

<%= link_to 'New Debit', new_debit_path, class: "btn btn-mini btn-success active"%>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debits.each do |debit| %>
      <tr>
        <td><%= debit.name %></td>
        <td><%= link_to 'Show', debit %></td>
        <td><%= link_to 'Edit', edit_debit_path(debit) %></td>
        <td><%= link_to 'Destroy', debit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/debits/new.html.erb
<h1>New debit</h1>

<%= render 'form' %>

<%= link_to 'Back', debits_path %>

app/views/debits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @debit.name %>
</p>

<%= link_to 'Edit', edit_debit_path(@debit) %> |
<%= link_to 'Back', debits_path %>

app/views/debits/summary.html.erb
<h1>Ledger Details</h1>

<%= link_to 'New Transaction', new_cashbook_path, class: "btn btn-mini btn-success active" %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Ledger</th>
      <th>Debit</th>
      <th>Credit</th>
      <th>Amount</th>      
    </tr>
  </thead>

  <tbody>
    <% @transactions_debit.each do |transaction| %>
      <tr>
        <td><%= transaction.date.strftime("%d-%b-%Y") %></td>
        <td><%= transaction.debit.name%></td>
        <td><%= transaction.credit.name %></td>
        <td><%= transaction.amount %></td>      
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Accounting" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Accounting</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Debit Ledgers", debits_path  %></li>
              <li><%= link_to "Credit Ledgers", credits_path %></li>
              <li><%= link_to "Transactions", cashbooks_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/ledgers/_form.html.erb
<%= form_for(@ledger) do |f| %>
  <% if @ledger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ledger.errors.count, "error") %> prohibited this ledger from being saved:</h2>

      <ul>
      <% @ledger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ledgers/summary.html.erb
<h1>Ledger Details</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Ledger</th>
      <th>Debit</th>
      <th>Credit</th>
      <th>Amount</th>      
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |credit| %>
      <tr>
        <td><%= credit.date %></td>
        <td><%= credit.ledger.name%></td>
        <td><%= credit.debit_or_credit %></td>
        <td><%= credit.amount %></td>      
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_cashbook_path %>